server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pebbles.cjtx83kncko7.ap-northeast-2.rds.amazonaws.com/pebbles

    username: admin
    password: 20000118

  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true